[gcp_service_account]
type = "service_account"
project_id = "youtube-api-client-480202"
private_key_id = "a7ff192bb..."
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIB...==
-----END PRIVATE KEY-----
"""
client_email = "youtube-data-api-viewer@youtube-api-client-480202.iam.gserviceaccount.com"
client_id = "113566733..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/youtube-data-api-viewer%40youtube-api-client-480202.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
